version: 1
disable_existing_loggers: False

filters:
  masking:
    (): logging_.filters.maskingfilter.MaskingFilter
    mask: "*****"
    patterns:
      - "AToken:[a-z0-9]+"
      - "(?<=(?:\"|')password(?:\"|'): (?:\"|'))[^\"']+(?=(?:\"|'))"
      - "(?<=(?:\"|')Authorization(?:\"|'): (?:\"|')Basic )[^\"']+(?=(?:\"|'))"
      - "(?<=(?:\"|')Auth(?:\"|'): \\()(.*)(?=\\), (?:\"|'))"
      - "(?<=(?:\"|')access_token(?:\"|'): (?:\"|'))[^\"']+(?=(?:\"|'))"
  appname:
    (): logging_.filters.namefilter.AppFilter
  requestid:
    (): logging_.filters.requestId_filter.RequestIdFilter
  scfilter:
    (): logging_.filters.statusCodeFilter.StatusCodeFilter
  epfilter:
    (): logging_.filters.endpoint_filter.EndpointFilter
  sysepfilter:
    (): logging_.filters.systemEndpointFilter.SystemEndpointFilter

formatters:
  simple:
    format: '%(request_id)s - %(asctime)s - %(source)s - %(levelname)s - %(message)s'

handlers:
  socket:
    (): logging_.handlers.jsonsockethandler.JSONSocketHandler
    filters:
      - masking
      - appname
      - requestid
      - scfilter
      - epfilter
      - sysepfilter
    formatter: simple
    host: log-receiver
    # host: 'localhost'
    port: 9021

root:
  handlers:
    - socket
  level: INFO